### ISSUE TITLE
`assetTransforms` service is now `imageTransforms` service

### ISSUE THREAD

**Issue by engram-design** [craftcms/rector#1]
Leaving a quick note that the following should be handled:

```
Craft::$app->getAssetTransforms()->...
```

to

```
Craft::$app->getImageTransforms()->...
```

If I figure out how to make custom rules, I'll add a PR.

**Comment by brandonkelly** [comment]
It would be pretty easily doable to make that one single change, but there’s more breaking changes within the service than just its name. So decided this is better off being done manually.
