### ISSUE TITLE
Call to undefined method PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getParamImmediatelyInvokedCallableTagValues() is back

### ISSUE THREAD

**Issue by sunscreem** [craftcms/rector#22]
### Description

I'm upgrading a Craft 4 site to Craft 5 and following [their instructions for upgrading a custom plugin](https://craftcms.com/docs/5.x/extend/updating-plugins.html#rector).

When running `vendor/bin/rector process [directory] --config vendor/craftcms/rector/sets/craft-cms-50.php` the process seems to run okay (the progress bar appears). Then I get this error multiple times (different file names) and no changes are made.

```
[ERROR] Could not process "plugins/[x]/src/variables/[x].php" file, due to:  
         "Call to undefined method                                                                        
         PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode::getParamImmediatelyInvokedCallableTagValues()". On   
         line: 307  
```

### Steps to reproduce

1. Install as per Craft instructions 
2. Run the command above.

### Additional info

- Craft version: 4.9.3
- PHP version: 8.2.3

The version of the this I'm using is `dev-main`

**Comment by sunscreem** [comment]
It maybe the same issue as https://github.com/craftcms/rector/pull/19, however I can confirm my `vendor/craftcms/rector/composer.json` is requiring `"rector/rector": "^0.19.2"`

**Comment by johnnynotsolucky** [comment]
@sunscreem this can also be resolved by downgrading phpstan and phpdoc-parser:

```json
    "require-dev": {
        ...
        "phpstan/phpdoc-parser": "1.26.0",
        "phpstan/phpstan": "1.10.60",
    }
```

**Comment by sunscreem** [comment]
@johnnynotsolucky @TomasVotruba All working now - using latest version. Thank you both.

**Comment by Geovanek** [comment]
Is back to me today with Larastan v3.6 and rector 2.1.2
