### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xswirelab** [craftcms/rector#9]
Hi there,

I know this is not the (preferred) way of contacting you when having questions. I do not expect an answer and you will probably close the ticket. 
Anyways...with pain in my heart I do try my luck, cause I want to know if you have a product roadmap? I expect to be using this package soon and was wondering if there are any things still being planned or worked on.

Apologies and best regards,

Xander

**Comment by TomasVotruba** [comment]
Hi Xander,

thanks for askin. As far as I know, this package is finished as it is.
Is there some feature you're missing and would like to see here?

The exact code snippet of before/after are the best to understand for me :)

**Comment by xswirelab** [comment]
Thank you Tomas, but I don't have technical questions..yet.

I was updating all my static analysis & fixer scripts and wondered about how Rector could help our company manage updating of our client websites. So I stumbled upon this repo and was just curious about this package's state. It seems rather useful for us. 

Again, thanks for your reply. 
I wish you all the best.

Xander

**Comment by TomasVotruba** [comment]
Thank you 😊
Just go for it 👍
